### ISSUE TITLE
Using the simulator: Add a Webots screenshot to the 'overview' page

### ISSUE THREAD

**Issue by Adimote** [srobo/docs#550] opened 2023-10-19 23:33 UTC

**Comment by PeterJCLaw** [comment] 2023-10-20 21:18
@Adimote is this a duplicate of https://github.com/srobo/docs/issues/543?

**Comment by PeterJCLaw** [comment] 2023-10-20 22:21
> @Adimote is this a duplicate of #543?

I suspect probably not. I'm planning on doing the following:
- adding a generic image of webots to the page about using the simulator
- adding a game-specific image of just the world (arena) to the overview page

The latter will resolve #543

**Closed** 2023-10-21 11:31 UTC
